package com.example.netmaster.ui

import android.app.Application
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.netmaster.ai.*
import com.example.netmaster.data.*
import com.example.netmaster.domain.*
import kotlin.math.cos
import kotlin.math.sin

@Composable
fun NetMasterApp(vm:NetMasterViewModel){
    var tab by remember{mutableIntStateOf(0)};var selectedLevel by remember{mutableStateOf<Int?>(null)};var selectedLesson by remember{mutableStateOf<Lesson?>(null)};var searchOpen by remember{mutableStateOf(false)}
    val tabs=listOf("خانه" to Icons.Default.Home,"یادگیری" to Icons.Default.MenuBook,"Lab" to Icons.Default.Build,"آزمون" to Icons.Default.Quiz,"یادداشت" to Icons.Default.EditNote,"AI" to Icons.Default.AutoAwesome,"Ops" to Icons.Default.Dns,"Simulator" to Icons.Default.Terminal,"Engineer OS" to Icons.Default.Hub)
    Scaffold(topBar={if(selectedLesson==null&&selectedLevel==null&&!searchOpen)TopAppBar(title={Text("NetMaster",fontWeight=FontWeight.Bold)},actions={IconButton({searchOpen=true}){Icon(Icons.Default.Search,"جستجو")}})},bottomBar={NavigationBar{tabs.forEachIndexed{i,x->NavigationBarItem(i==tab,{tab=i;selectedLevel=null;selectedLesson=null;searchOpen=false},{Icon(x.second,x.first)},label={Text(x.first,fontSize=10.sp)})}}}){pad->Box(Modifier.padding(pad).fillMaxSize()){when{searchOpen->Search(vm){selectedLesson=it;searchOpen=false};selectedLesson!=null->LessonScreen(selectedLesson!!,vm){selectedLesson=null};selectedLevel!=null->LevelScreen(vm,selectedLevel!!){selectedLesson=it};tab==0->Dashboard(vm){tab=1};tab==1->Learning(vm){selectedLevel=it};tab==2->Labs(vm);tab==3->Quiz(vm){selectedLesson=it};tab==4->Notes(vm);tab==5->AICenter(vm);tab==6->OperationsCenter(vm);tab==7->SimulatorCenter(vm);tab==8->V11EngineerOS(vm);else->Dashboard(vm){tab=0}}}}}
}

@Composable fun Dashboard(vm:NetMasterViewModel,openLearning:()->Unit){
    val c=vm.curriculum.collectAsState().value?:return;val p=vm.progress.collectAsState().value;val total=c.levels.sumOf{it.lessons.size};val done=p.values.count{it.completed};val mastered=p.values.count{it.mastery==Mastery.MASTERED.name};val deep=vm.deepLessonCount.collectAsState().value;val scenarios=vm.scenarioCount.collectAsState().value
    LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
        item{Text("NetMaster — مرکز مهندسی IT و شبکه",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Offline-first • Learning • Labs • RAG • AI • Evidence Correlation • Digital Twin • Operations")}
        item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){Box(Modifier.weight(1f)){MetricCard("درس",done.toString()+" / "+total,if(total==0)0f else done.toFloat()/total)};Box(Modifier.weight(1f)){MetricCard("مسلط",mastered.toString(),if(total==0)0f else mastered.toFloat()/total)}}}
        item{Card(onClick=openLearning){Column(Modifier.padding(16.dp)){Text("مسیر حرفه‌ای",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("${c.levels.size} سطح یکپارچه • ${vm.catalogCount.collectAsState().value} رکورد قابل جست‌وجو");Text("Concept → Packet/State → Config → Verification → Troubleshooting → Lab → Project")}}}
        item{Card{Column(Modifier.padding(16.dp)){Text("Unified Engineering Pack",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("$deep درس عمیق • $scenarios سناریوی Break/Fix • ${vm.labCatalog.collectAsState().value?.labs?.size ?: 0} Lab");Text("Ethernet • VLAN • STP • Routing • OSPF/BGP • DNS/AD • MikroTik • Cisco • Linux • VMware • Zabbix • Wireshark • Wazuh • Cloud")}}}
        item{AboutCreatorCard()}
        item{Text("شروع سریع",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)}
        items(c.levels.take(12)){l->Card{Column(Modifier.padding(12.dp)){Text("${l.id}. ${l.title}",fontWeight=FontWeight.Bold);Text("${l.lessons.size} درس")}}}
    }
}
@Composable
fun AboutCreatorCard(){
    Card(Modifier.fillMaxWidth()){
        Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){
            Text("درباره NetMaster",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)
            Text("NetMaster Learning — Unified Engineering")
            Text("سازنده: مهندس مسعود جوکار",fontWeight=FontWeight.Bold)
            Text("تماس: 09132184122")
            Text("نسخه 11.0.0")
            Text("آموزش شبکه • Lab • AI/RAG • شبیه‌ساز • PCAP • عیب‌یابی • Incident")
        }
    }
}
@Composable fun MetricCard(t:String,v:String,p:Float){Card{Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(t,fontWeight=FontWeight.Bold);Text(v);LinearProgressIndicator(progress={p.coerceIn(0f,1f)},Modifier.fillMaxWidth())}}}
@Composable fun Learning(vm:NetMasterViewModel,onLevel:(Int)->Unit){val c=vm.curriculum.collectAsState().value?:return;LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text("Learning Engine",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Concept → Architecture → Packet/State → Configuration → Verification → Troubleshooting → Lab → Quiz → Mastery")};items(c.levels){l->Card(onClick={onLevel(l.id)}){Column(Modifier.padding(16.dp)){Text("${l.id}. ${l.title}",fontWeight=FontWeight.Bold);Text(l.summary);Text("${l.lessons.size} درس")}}}}}
@Composable fun LevelScreen(vm:NetMasterViewModel,id:Int,onLesson:(Lesson)->Unit){val l=vm.curriculum.collectAsState().value?.levels?.firstOrNull{it.id==id}?:return;val p=vm.progress.collectAsState().value;LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text("سطح ${l.id}: ${l.title}",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(l.summary)};items(l.lessons){x->Card(onClick={onLesson(x)}){Column(Modifier.padding(14.dp)){Text(x.title,fontWeight=FontWeight.Bold);Text(x.goal);Text(masteryLabel(p[x.id]?.mastery?:Mastery.UNKNOWN.name))}}}}}
@Composable fun LessonScreen(x:Lesson,vm:NetMasterViewModel,back:()->Unit){val b=vm.bookmarks.collectAsState().value;val pr=vm.progress.collectAsState().value[x.id];var note by remember{mutableStateOf("")};LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){TextButton(back){Text("بازگشت")};IconButton({vm.toggleBookmark(x.id)}){Icon(if(b.contains(x.id))Icons.Default.Bookmark else Icons.Default.BookmarkBorder,"نشانک")}}};item{Text(x.title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)};section("هدف",x.goal);section("مفهوم ساده",x.simple);section("مفهوم فنی",x.technical);section("تحلیل عمیق",x.deepTechnical);section("Packet / State Walkthrough",x.packetWalkthrough);section("دیاگرام",x.diagram);section("Configuration Playbook",x.configurationPlaybook);section("Commands",x.platformCommands.ifBlank{x.commands});section("Real Scenario",x.realScenario);section("Traffic",x.traffic);section("Lab",x.lab);bulletSection("Lab Steps",x.labSteps);section("Troubleshooting",x.troubleshooting);bulletSection("Evidence",x.evidenceChecklist);bulletSection("Interview",x.interviewQuestions);bulletSection("اشتباهات رایج",x.commonMistakes);bulletSection("Mastery Path",x.masteryPath);item{Text("Mastery",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){Mastery.entries.forEach{m->FilterChip(pr?.mastery==m.name,{vm.setMastery(x.id,m)},label={Text(masteryLabel(m.name))})}}};item{OutlinedTextField(note,{note=it},Modifier.fillMaxWidth(),minLines=4,label={Text("یادداشت شخصی")});Button({if(note.isNotBlank()){vm.addNote(x.id,x.title,note);note=""}},Modifier.fillMaxWidth()){Text("ذخیره یادداشت")}};item{Text("Quiz",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);x.quiz.forEach{q->Card(Modifier.padding(vertical=3.dp)){Column(Modifier.padding(12.dp)){Text(q.q,fontWeight=FontWeight.Bold);Text("پاسخ کلیدی: ${q.a}")}}}}}}
@Composable fun section(t:String,b:String){if(b.isNotBlank())Column(Modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(4.dp)){Text(t,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Card{Text(b,Modifier.padding(14.dp))}}}
@Composable fun bulletSection(t:String,items:List<String>){if(items.isNotEmpty())Column{Text(t,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Card{Column(Modifier.padding(14.dp)){items.forEach{Text("• $it",Modifier.padding(vertical=2.dp))}}}}}

@Composable fun Labs(vm:NetMasterViewModel){val twin=vm.twin.collectAsState().value;val faults=vm.twinEngine.faults();LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Digital Twin Lab",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Fault Injection + Evidence + Simulator State")};item{TwinGraph(twin.nodes,twin.links,Modifier.fillMaxWidth().height(250.dp))};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.resetTwin()}){Text("Reset Twin")};Button({vm.saveSimulatorSnapshot("manual")}){Text("Snapshot")}}};item{Card{Column(Modifier.padding(14.dp)){Text("State",fontWeight=FontWeight.Bold);twin.simulator?.let{s->Text("VLANs: ${s.vlans.sorted().joinToString()}");Text("Routes: ${s.routes.size} • ARP: ${s.arp.size}");Text("DNS ${if(s.dnsHealthy)"OK" else "FAIL"} • Firewall ${if(s.firewallHealthy)"OK" else "FAIL"} • NAT ${if(s.natHealthy)"OK" else "FAIL"}");Text("OSPF ${if(s.ospfHealthy)"UP" else "DEGRADED"} • BGP ${if(s.bgpHealthy)"UP" else "DOWN"} • QoS ${if(s.qosHealthy)"OK" else "CONGESTED"}")}}}};item{Text("Fault Injection",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)};items(faults){f->Card(onClick={vm.injectFault(f)}){Column(Modifier.padding(14.dp)){Text(f.title,fontWeight=FontWeight.Bold);Text(f.description);Text("Severity: ${f.severity} • Target: ${f.target}")}}};twin.activeFault?.let{f->item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Fault فعال: ${f.title}",fontWeight=FontWeight.Bold);Text("Hint: ${f.hint}");Button({vm.recordEvidence("بررسی ${f.target}")}){Text("ثبت Evidence")};Text("Evidence: ${twin.evidence.joinToString()}");Text("Score: ${twin.score}")}}}}}}

@Composable fun TwinGraph(nodes:List<TwinNode>,links:List<TwinLink>,modifier:Modifier){Canvas(modifier.background(MaterialTheme.colorScheme.surfaceVariant)){if(nodes.isEmpty())return@Canvas;val center=Offset(size.width/2,size.height/2);val radius=minOf(size.width,size.height)*0.34f;val pos=nodes.mapIndexed{idx,n->n.id to Offset(center.x+radius*cos(idx*2.0*Math.PI/nodes.size).toFloat(),center.y+radius*sin(idx*2.0*Math.PI/nodes.size).toFloat())}.toMap();links.forEach{e->pos[e.from]?.let{a->pos[e.to]?.let{b->drawLine(MaterialTheme.colorScheme.outline,a,b,3f)}}};nodes.forEach{n->val p=pos[n.id]?:center;drawCircle(MaterialTheme.colorScheme.primary,18f,p);drawContext.canvas.nativeCanvas.drawText(n.name,p.x-48,p.y-25,android.graphics.Paint().apply{color=android.graphics.Color.DKGRAY;textSize=20f})}}}

@Composable fun Quiz(vm:NetMasterViewModel,open:(Lesson)->Unit){val c=vm.curriculum.collectAsState().value?:return;val ls=remember(c){c.levels.flatMap{it.lessons}.filter{it.quiz.isNotEmpty()}};var i by remember{mutableIntStateOf(0)};if(ls.isEmpty())return;val l=ls[i%ls.size];LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Quiz Engine",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold)};item{Card{Column(Modifier.padding(14.dp)){Text(l.title,fontWeight=FontWeight.Bold);l.quiz.forEach{Text(it.q,Modifier.padding(top=10.dp));Text("پاسخ کلیدی: ${it.a}")}}}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({i++},Modifier.weight(1f)){Text("بعدی")};OutlinedButton({open(l)},Modifier.weight(1f)){Text("درس")}}}}}
@Composable fun Notes(vm:NetMasterViewModel){val n=vm.notes.collectAsState().value;LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{Text("Knowledge Base",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("یادداشت‌ها، یافته‌ها و تجربه‌های واقعی")};if(n.isEmpty())item{Text("هنوز یادداشتی ثبت نشده است.")}else items(n){x->Card{Column(Modifier.padding(14.dp)){Text(x.title,fontWeight=FontWeight.Bold);if(x.tags.isNotBlank())Text("# ${x.tags}");Text(x.body)}}}}}

@Composable fun Search(vm:NetMasterViewModel,onLesson:(Lesson)->Unit){var q by remember{mutableStateOf("")};val hits=vm.searchResults.collectAsState().value;LaunchedEffect(q){if(q.length>=2)vm.searchAll(q)};Column(Modifier.padding(16.dp)){Text("جستجوی سراسری",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("درس + Track + Deep + Scenario + Lab + AI Playbook + Note + Incident + Config + PCAP");OutlinedTextField(q,{q=it},Modifier.fillMaxWidth(),label={Text("پروتکل، Command، IP، Incident، Note...")});LazyColumn{items(hits){h->ListItem(headlineContent={Text(h.title)},supportingContent={Text("${h.kind} • ${h.snippet}")},trailingContent={if(h.kind=="LESSON")TextButton({val c=vm.curriculum.value;val lesson=c?.levels?.flatMap{it.lessons}?.firstOrNull{it.id==h.id};if(lesson!=null)onLesson(lesson)}){Text("باز")}})}}}}

@Composable fun AICenter(vm:NetMasterViewModel){var mode by remember{mutableStateOf(AiMode.TROUBLESHOOTER)};var prompt by remember{mutableStateOf("")};var endpoint by remember{mutableStateOf("http://10.0.2.2:11434")};var model by remember{mutableStateOf("llama3.2")};var protocol by remember{mutableStateOf(LocalLlmProtocol.OLLAMA)};val r=vm.aiResponse.collectAsState().value;val backend=vm.aiBackend.collectAsState().value;val vectors=vm.vectorCount.collectAsState().value;LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("AI Engineering Center",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Backend: $backend • Vector chunks: $vectors")};item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Local LLM",fontWeight=FontWeight.Bold);OutlinedTextField(endpoint,{endpoint=it},Modifier.fillMaxWidth(),label={Text("Local endpoint")});OutlinedTextField(model,{model=it},Modifier.fillMaxWidth(),label={Text("Model")});Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){FilterChip(protocol==LocalLlmProtocol.OLLAMA,{protocol=LocalLlmProtocol.OLLAMA},label={Text("Ollama")});FilterChip(protocol==LocalLlmProtocol.OPENAI_COMPATIBLE,{protocol=LocalLlmProtocol.OPENAI_COMPATIBLE},label={Text("OpenAI-compatible")})};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.configureLocalAi(endpoint,model,protocol);vm.setAiBackend(true)}){Text("Local LLM")};OutlinedButton({vm.setAiBackend(false)}){Text("Offline")}}}};item{Text("AI Modes",fontWeight=FontWeight.Bold)};item{Column(verticalArrangement=Arrangement.spacedBy(4.dp)){AiMode.entries.chunked(3).forEach{row->Row(horizontalArrangement=Arrangement.spacedBy(4.dp)){row.forEach{FilterChip(mode==it,{mode=it},label={Text(it.name,fontSize=9.sp)})}}}}};item{OutlinedTextField(prompt,{prompt=it},Modifier.fillMaxWidth(),minLines=4,label={Text("سؤال، Symptom، Configuration یا Incident")});Button({vm.askAi(mode,prompt)},enabled=prompt.isNotBlank(),Modifier.fillMaxWidth()){Text("تحلیل با AI + RAG")}};r?.let{item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(it.title,fontWeight=FontWeight.Bold);Text(it.answer);it.hypotheses.forEach{h->Text("فرضیه: ${h.title} (${h.confidence}%)");Text("Evidence: ${h.evidenceToCheck.joinToString()}")};if(it.nextTests.isNotEmpty())Text("Next Tests: ${it.nextTests.joinToString()}");if(it.safetyNotes.isNotEmpty())bulletSection("Safety",it.safetyNotes)}}}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.rebuildVectorIndex()}){Text("Rebuild RAG")};Button({vm.buildKnowledgeGraph()}){Text("Build Graph")};Button({vm.exportBackup()}){Text("Backup")}};vm.exported.collectAsState().value?.let{f->Text("Backup: ${f.name}")}}}}

fun masteryLabel(v:String)=when(v){Mastery.UNKNOWN.name->"بلد نیستم";Mastery.REVIEW.name->"نیاز به مرور";Mastery.KNOWN.name->"بلدم";Mastery.MASTERED.name->"مسلط هستم";else->v}

@Composable fun OperationsCenter(vm:NetMasterViewModel){
    val incidents by vm.incidents.collectAsState();val captures by vm.captures.collectAsState();val configs by vm.configs.collectAsState();val due by vm.dueReviews.collectAsState();val kg by vm.knowledge.collectAsState();val selected by vm.selectedIncident.collectAsState();val packets by vm.filteredPackets.collectAsState();val filterError by vm.filterError.collectAsState();
    var incidentTitle by remember{mutableStateOf("")};var symptom by remember{mutableStateOf("")};var severity by remember{mutableStateOf("MEDIUM")};var captureName by remember{mutableStateOf("")};var captureText by remember{mutableStateOf("")};var filter by remember{mutableStateOf("")};var oldCfg by remember{mutableStateOf("")};var newCfg by remember{mutableStateOf("")};var diff by remember{mutableStateOf<List<ConfigDiffLine>>(emptyList())};var device by remember{mutableStateOf("")};var vendor by remember{mutableStateOf("MikroTik")};var label by remember{mutableStateOf("")};var cfgText by remember{mutableStateOf("")};var root by remember{mutableStateOf("")};var resolution by remember{mutableStateOf("")}
    val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){uri->uri?:return@rememberLauncherForActivityResult;runCatching{val data=vm.getApplication<Application>().contentResolver.openInputStream(uri)?.use{it.readBytes()}?:return@runCatching;vm.importPcap(uri.lastPathSegment?.substringAfterLast('/')?.ifBlank{"capture"}?:"capture.pcap",data)}}
    if(selected!=null){IncidentWorkspaceScreen(selected!!,root,{root=it},resolution,{resolution=it},{vm.closeIncident(selected!!.incident,root,resolution)},{vm.setIncidentStatus(selected!!.incident,"INVESTIGATING")},{vm.openIncident(selected!!.incident.id)},{vm.addIncidentEvidence(selected!!.incident.id,it.first,it.second)});return}
    LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
        item{Text("Operations Engineering",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Vector RAG • Graph • PCAP • Filters • Config • Incidents • Review")}
        item{Card{Column(Modifier.padding(14.dp)){Text("Smart Review",fontWeight=FontWeight.Bold);Text("سررسید: ${due.size}");due.take(8).forEach{r->Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(r.lessonId);Row{TextButton({vm.gradeReview(r.lessonId,5)}){Text("بلدم")};TextButton({vm.gradeReview(r.lessonId,2)}){Text("مرور")}}}}}}}
        item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Incident Workspace",fontWeight=FontWeight.Bold);OutlinedTextField(incidentTitle,{incidentTitle=it},Modifier.fillMaxWidth(),label={Text("عنوان Incident")});OutlinedTextField(symptom,{symptom=it},Modifier.fillMaxWidth(),minLines=2,label={Text("Symptom / Scope")});OutlinedTextField(severity,{severity=it},Modifier.fillMaxWidth(),label={Text("Severity")});Button({if(incidentTitle.isNotBlank()){vm.createIncident(incidentTitle,symptom,severity);incidentTitle="";symptom=""}},Modifier.fillMaxWidth()){Text("ایجاد Incident")};incidents.take(8).forEach{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text("#${it.id} ${it.title}",fontWeight=FontWeight.Bold);Text("${it.status} • ${it.severity}")};TextButton({vm.openIncident(it.id)}){Text("Workspace")}}}}}
        item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("PCAP / PCAPNG",fontWeight=FontWeight.Bold);Button({picker.launch(arrayOf("application/octet-stream","application/vnd.tcpdump.pcap","application/vnd.tcpdump.pcapng","*/*"))},Modifier.fillMaxWidth()){Text("انتخاب Capture File")};OutlinedTextField(captureName,{captureName=it},Modifier.fillMaxWidth(),label={Text("نام Capture متنی")});OutlinedTextField(captureText,{captureText=it},Modifier.fillMaxWidth(),minLines=4,label={Text("یا خروجی Capture را Paste کن")});Button({if(captureText.isNotBlank()){vm.importCapture(captureName.ifBlank{"capture"},captureText);captureText=""}},Modifier.fillMaxWidth()){Text("تحلیل متن")};captures.take(5).forEach{Text("#${it.id} ${it.name} • ${it.format} • ${it.packetCount} packets\n${it.protocolSummary}")}}}}
        item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Wireshark-like Filter",fontWeight=FontWeight.Bold);OutlinedTextField(filter,{filter=it},Modifier.fillMaxWidth(),label={Text("tcp and tcp.port == 443")});Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.filterCapture(filter)}){Text("Filter")};OutlinedButton({vm.resetPacketFilter();filter=""}){Text("Reset")}};filterError?.let{Text("Filter error: $it")};packets.take(30).forEach{p->Text("#${p.number} ${p.source} → ${p.destination} ${p.protocol} ${p.srcPort?:""}:${p.dstPort?:""} ${p.tcpFlags} ${p.info}",fontFamily=FontFamily.Monospace,fontSize=10.sp)}}}}
        item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Config Snapshots + Diff",fontWeight=FontWeight.Bold);OutlinedTextField(device,{device=it},Modifier.fillMaxWidth(),label={Text("Device ID")});OutlinedTextField(vendor,{vendor=it},Modifier.fillMaxWidth(),label={Text("Vendor")});OutlinedTextField(label,{label=it},Modifier.fillMaxWidth(),label={Text("Snapshot label")});OutlinedTextField(cfgText,{cfgText=it},Modifier.fillMaxWidth(),minLines=3,label={Text("Configuration snapshot")});Button({if(device.isNotBlank()&&cfgText.isNotBlank())vm.saveConfig(device,vendor,label.ifBlank{"snapshot"},cfgText)},Modifier.fillMaxWidth()){Text("ذخیره Snapshot")};Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){OutlinedTextField(oldCfg,{oldCfg=it},Modifier.weight(1f),minLines=3,label={Text("Old")});OutlinedTextField(newCfg,{newCfg=it},Modifier.weight(1f),minLines=3,label={Text("New")})};Button({diff=vm.configDiffEngine.diff(oldCfg,newCfg)},Modifier.fillMaxWidth()){Text("Diff")};diff.take(50).forEach{Text("${it.type} ${it.lineNumber}: ${it.line}",fontFamily=FontFamily.Monospace)};configs.take(5).forEach{Text("#${it.id} ${it.deviceId} • ${it.vendor} • ${it.label} • ${it.fingerprint}")}}}}
        item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Knowledge Graph",fontWeight=FontWeight.Bold);Text("Nodes: ${kg.nodes.size} • Edges: ${kg.edges.size}");Button({vm.buildKnowledgeGraph()},Modifier.fillMaxWidth()){Text("Build / Update Graph")};if(kg.nodes.isNotEmpty())GraphView(kg)}}}
    }
}

@Composable fun GraphView(kg:KnowledgeGraphView){Canvas(Modifier.fillMaxWidth().height(320.dp).background(MaterialTheme.colorScheme.surfaceVariant)){val nodes=kg.nodes.take(90);if(nodes.isEmpty())return@Canvas;val center=Offset(size.width/2,size.height/2);val radius=minOf(size.width,size.height)*0.36f;val pos=nodes.mapIndexed{idx,n->n.id to Offset(center.x+radius*cos(idx*2.0*Math.PI/nodes.size).toFloat(),center.y+radius*sin(idx*2.0*Math.PI/nodes.size).toFloat())}.toMap();kg.edges.filter{pos.containsKey(it.fromId)&&pos.containsKey(it.toId)}.take(240).forEach{e->drawLine(MaterialTheme.colorScheme.outline,pos[e.fromId]!!,pos[e.toId]!!,2f)};nodes.forEach{n->val p=pos[n.id]!!;drawCircle(if(n.kind=="TAG")MaterialTheme.colorScheme.secondary else MaterialTheme.colorScheme.primary,10f,p)}}}

@Composable fun IncidentWorkspaceScreen(ws:IncidentWorkspace,root:String,onRoot:(String)->Unit,resolution:String,onResolution:(String)->Unit,onResolve:()->Unit,onInvestigate:()->Unit,onBack:()->Unit,onEvidence:(Pair<String,String>)->Unit){var evidence by remember{mutableStateOf("")};LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("Incident #${ws.incident.id}",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);TextButton(onBack){Text("بازگشت")}};Text(ws.incident.title);Text("${ws.incident.status} • ${ws.incident.severity}")};item{section("Symptom",ws.incident.symptom)};item{Text("Evidence Timeline",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);ws.evidence.forEach{Card{Text("${it.type}: ${it.value}",Modifier.padding(12.dp))}};ws.events.forEach{Card{Text("${it.eventType} • ${it.message}",Modifier.padding(10.dp))}}};item{Text("Linked Captures",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);ws.linkedCaptures.forEach{Text("#${it.id} ${it.name} • ${it.packetCount} packets • ${it.protocolSummary}")}};item{Text("Linked Configs",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);ws.linkedConfigs.forEach{Text("#${it.id} ${it.deviceId} • ${it.vendor} • ${it.label}")}};item{OutlinedTextField(evidence,{evidence=it},Modifier.fillMaxWidth(),label={Text("Evidence جدید")});Button({if(evidence.isNotBlank()){onEvidence("NOTE" to evidence);evidence=""}},Modifier.fillMaxWidth()){Text("ثبت Evidence")}};item{OutlinedTextField(root,onRoot,Modifier.fillMaxWidth(),label={Text("Root Cause")});OutlinedTextField(resolution,onResolution,Modifier.fillMaxWidth(),minLines=3,label={Text("Resolution")});Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onInvestigate){Text("Investigate")};Button(onResolve){Text("Resolve")}}}}

@Composable fun SimulatorCenter(vm:NetMasterViewModel){val twin=vm.twin.collectAsState().value;val coach=vm.coach.collectAsState().value;val output=vm.simOutput.collectAsState().value;var command by remember{mutableStateOf("")};var symptom by remember{mutableStateOf("")};LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("Network Command Simulator",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Safe sandbox — هیچ Commandای روی تجهیزات واقعی اجرا نمی‌شود.")};item{TwinGraph(twin.nodes,twin.links,Modifier.fillMaxWidth().height(250.dp))};item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("Simulator State",fontWeight=FontWeight.Bold);twin.simulator?.let{s->Text("VLAN ${s.vlans.sorted().joinToString()} • Routes ${s.routes.size} • ARP ${s.arp.size}");Text("DNS=${s.dnsHealthy} NAT=${s.natHealthy} FW=${s.firewallHealthy} OSPF=${s.ospfHealthy} BGP=${s.bgpHealthy} STP=${s.stpHealthy} QoS=${s.qosHealthy}")};OutlinedTextField(command,{command=it},Modifier.fillMaxWidth(),label={Text("show ip route / show vlan / ping / nslookup / disable dns")});Button({vm.runSimulator(command)},Modifier.fillMaxWidth()){Text("Execute in Simulator")};Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedButton({vm.saveSimulatorSnapshot("manual")}){Text("Snapshot")};OutlinedButton({vm.resetTwin()}){Text("Reset")}};if(output.isNotBlank())Text(output,fontFamily=FontFamily.Monospace)}}};item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("AI Autonomous Troubleshooting Coach",fontWeight=FontWeight.Bold);OutlinedTextField(symptom,{symptom=it},Modifier.fillMaxWidth(),minLines=2,label={Text("Symptom")});Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({vm.startCoach(symptom)}){Text("Start Coach")};OutlinedButton({vm.coachNext()}){Text("Next Test")}};coach?.let{c->Text("${c.status} • Scenario=${c.scenarioId?:"generic"}");Text("Step ${minOf(c.currentIndex+1,c.steps.size)} / ${c.steps.size}",fontWeight=FontWeight.Bold);c.steps.getOrNull(c.currentIndex)?.let{s->Text("${s.title}\n${s.reason}\nCommand: ${s.command}\nExpected: ${s.expected}")};if(c.evidence.isNotEmpty())Text("Evidence:\n${c.evidence.takeLast(8).joinToString("\n")}");if(c.findings.isNotEmpty())Text("Findings: ${c.findings.joinToString(" | ")}")}}}};item{Text("Model: Evidence → Hypothesis → Test → Result → Finding → Human Validation → Fix/Rollback")}}
}

@Composable
fun V11EngineerOS(vm:NetMasterViewModel){
    val investigation=vm.v11Investigation.collectAsState().value
    val passport=vm.v11Passport.collectAsState().value
    val selectedFault=vm.v11SelectedFault.collectAsState().value
    val faults=vm.v11Faults.collectAsState().value
    var symptom by remember{mutableStateOf("")}
    var evidence by remember{mutableStateOf("")}
    var activeFault by remember{mutableStateOf<String?>(null)}
    LaunchedEffect(Unit){vm.computeV11Passport()}
    LazyColumn(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){
        item{Text("NetMaster V11 — Digital Network Engineer",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Evidence → Causality → First Divergence → Test → Root Cause → Verification")}
        item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Engineering Evidence Chain",fontWeight=FontWeight.Bold);Text("هر نتیجه باید به Evidence قابل ردیابی و یک Test قابل رد/تأیید متصل باشد.");OutlinedTextField(symptom,{symptom=it},Modifier.fillMaxWidth(),label={Text("Symptom")});OutlinedTextField(evidence,{evidence=it},Modifier.fillMaxWidth(),minLines=5,label={Text("Packet / Log / Config / Metric / Observation")});Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({if(symptom.isNotBlank())vm.investigateV11(symptom,evidence)}){Text("Investigate")};OutlinedButton({symptom="";evidence="";vm.clearV11()}){Text("Reset")}}}}
        investigation?.let{inv->
            item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text("First Divergence",fontWeight=FontWeight.Bold);Text(inv.firstDivergence);Text("Causal Chain",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);inv.causalChain.forEach{Text("${it.from}  —${it.relation}→  ${it.to}");Text("Evidence: ${it.evidence}",style=MaterialTheme.typography.bodySmall)} }}}
            item{Text("Hypotheses",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold)}
            items(inv.hypotheses){h->Card{Column(Modifier.padding(12.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(h.title,fontWeight=FontWeight.Bold);Text("${h.confidence}%")};h.basis.forEach{Text("• $it")};Text("Falsifier: ${h.falsifier}",style=MaterialTheme.typography.bodySmall);Text("Next test: ${h.nextTest}",style=MaterialTheme.typography.bodySmall)}}}
            if(inv.blastRadius.isNotEmpty())item{Card{Column(Modifier.padding(14.dp)){Text("Dependency Blast Radius",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);inv.blastRadius.forEach{Text("${it.node} • ${it.relation} • impact ${it.impact}%");Text(it.why,style=MaterialTheme.typography.bodySmall)}}}}
            if(inv.relatedLessons.isNotEmpty())item{Card{Column(Modifier.padding(14.dp)){Text("Related Knowledge",fontWeight=FontWeight.Bold);inv.relatedLessons.forEach{Text("• $it")}}}}
        }
        item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text("Engineering Passport",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);if(passport!=null){Text("Overall Engineering Score: ${passport.overall}%",fontWeight=FontWeight.Bold);passport.competencies.forEach{Text("${it.name}: ${it.score}%");Text("Evidence: ${it.evidence}",style=MaterialTheme.typography.bodySmall)};Text("Strengths: ${passport.strengths.joinToString("، ")}");Text("Gaps to train: ${passport.gaps.joinToString("، ")}")}else Text("در حال محاسبه...")}}}
        item{Card{Column(Modifier.padding(14.dp)){Text("Controlled Failure Injection",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("خرابی کنترل‌شده برای Lab؛ فقط Twin داخلی تغییر می‌کند.");faults.forEach{f->Row(Modifier.fillMaxWidth().padding(vertical=4.dp),horizontalArrangement=Arrangement.SpaceBetween){Column(Modifier.weight(1f)){Text(f.title,fontWeight=FontWeight.Bold);Text("${f.layer} • ${f.firstDivergence}",style=MaterialTheme.typography.bodySmall)};Button({activeFault=f.id;vm.injectV11Fault(f.id)}){Text(if(activeFault==f.id)"Injected" else "Inject")}}}}}}
        selectedFault?.let{f->item{Card{Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text("Active Fault: ${f.title}",fontWeight=FontWeight.Bold);Text("Symptom: ${f.symptom}");Text("Expected Evidence",fontWeight=FontWeight.Bold);f.expectedEvidence.forEach{x->Text("• $x")};Text("First Divergence: ${f.firstDivergence}");Text("Remediation: ${f.remediation}");Text("Rollback: ${f.rollback}")}}}}
    }
}
