const A='assets/';let DB=[],ALIAS={},PLAYBOOKS=[],JOURNEYS=[],PROFILE={},EVIDENCE={},DEPS={},FAULTS={},PASSPORT={};
const $=s=>document.querySelector(s), norm=s=>(s||'').toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/\s+/g,' ').trim();
async function j(x){const r=await fetch(A+x);if(!r.ok)throw Error(x+' '+r.status);return r.json()}
function flat(c,d,s,l,ai){const a=[];for(const v of c.levels)for(const x of v.lessons)a.push(entry('lesson',x,v.title));for(const v of d.tracks)for(const x of v.lessons)a.push(entry('deep',x,v.title));for(const x of s.scenarios)a.push(entry('scenario',x,x.domain));for(const x of l.labs)a.push(entry('lab',x,x.phase));for(const x of (ai?.modes||[]))a.push(entry('ai',x,x.name||x.id||'AI'));return a}
function entry(type,data,group){const text=[data.title,data.goal,data.simple,data.technical,data.deepTechnical,data.internals,data.packetWalkthrough,data.packet_state_walkthrough,data.configurationPlaybook,data.platformCommands,data.failureMatrix,data.evidenceChecklist,data.lab,data.realScenario,data.expert_scenario,data.production_design,data.expertEngineering10x,data.deepEngineering10x,(data.tags||[]).join(' ')].map(x=>typeof x==='string'?x:JSON.stringify(x)).join(' ');return {type,id:data.id||data.title,title:data.title||data.name||'AI',group,text,tokens:[...new Set(norm(text).split(/[^\p{L}\p{N}._:/-]+/u).filter(x=>x.length>1))],data}}
function parse(q){let x=norm(q),filters={};x=x.replace(/(type|kind):([\w-]+)/g,(_,k,v)=>(filters.type=v,''));x=x.replace(/tag:([^\s]+)/g,(_,v)=>(filters.tag=v,''));x=x.replace(/level:([^\s]+)/g,(_,v)=>(filters.group=v,''));return {terms:x.split(/\s+/).filter(Boolean),filters}}
function hv(t){const v=new Map();for(const w of norm(t).split(/[^\p{L}\p{N}._:/-]+/u).filter(x=>x.length>1)){let h=0;for(let i=0;i<w.length;i++)h=((h<<5)-h+w.charCodeAt(i))|0;const k=Math.abs(h)%256;v.set(k,(v.get(k)||0)+1)}return v}
function cos(a,b){let d=0,aa=0,bb=0;for(const x of a.values())aa+=x*x;for(const x of b.values())bb+=x*x;for(const [k,x] of a)d+=x*(b.get(k)||0);return aa&&bb?d/Math.sqrt(aa*bb):0}
function expand(ts){const out=[...ts];for(const t of ts)for(const [k,vs] of Object.entries(ALIAS))if(k===t||vs.includes(t))out.push(k,...vs);return [...new Set(out)]}
function score(e,p){let s=cos(hv(p.terms.join(' ')),hv(e.text))*30;const terms=expand(p.terms),title=norm(e.title),hay=norm(e.text);for(const t of terms){if(title===t)s+=100;else if(title.includes(t))s+=45;if(hay.includes(t))s+=10;if(e.tokens.includes(t))s+=8}if(p.filters.type&&e.type!==p.filters.type)s=-999;if(p.filters.tag&&!(e.data.tags||[]).some(x=>norm(x)===norm(p.filters.tag)))s=-999;if(p.filters.group&&!norm(e.group).includes(norm(p.filters.group)))s=-999;return s}
function render(){const p=parse($('#q').value),type=$('#type').value;const rows=DB.map(e=>({e,s:score(e,p)})).filter(x=>x.s>0&&(type==='all'||x.e.type===type)).sort((a,b)=>b.s-a.s).slice(0,120);$('#searchMeta').textContent=`${rows.length} نتیجه • Hybrid lexical + hashed semantic ranking`;$('#results').innerHTML=rows.map((r,i)=>`<div class="result" data-i="${DB.indexOf(r.e)}"><div class="badge">${r.e.type}</div><h3>${esc(r.e.title)}</h3><small>${esc(r.e.group)} • score ${r.s.toFixed(1)}</small><p>${esc(snippet(r.e.text,p.terms))}</p><div>${(r.e.data.tags||[]).slice(0,6).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div>`).join('')||'<div class="card">نتیجه‌ای پیدا نشد.</div>';document.querySelectorAll('.result').forEach(x=>x.onclick=()=>show(DB[+x.dataset.i]))}
function snippet(t,terms){const s=String(t).replace(/\s+/g,' ');let pos=Infinity;for(const x of terms){const i=norm(s).indexOf(x);if(i>=0)pos=Math.min(pos,i)}return pos===Infinity?s.slice(0,330):s.slice(Math.max(0,pos-90),pos+300)}
function show(x){const d=x.data,sec=[['هدف',d.goal||d.objective],['Why',d.why_it_matters],['Mental Model',d.mental_model],['Internals',d.internals||d.deepTechnical],['State / Packet',(d.state_machine||'')+'\n'+(d.packet_state_walkthrough||d.packetWalkthrough||'')],['Configuration',d.configurationPlaybook||d.commands],['Verification',d.verification],['Failure Analysis',d.failure_analysis||d.troubleshooting],['Lab',d.lab],['Incident',d.expert_scenario||d.realScenario],['Production Design',d.production_design],['Forensics',d.forensics_drill],['Expert Questions',(d.expert_questions||[]).join('\n• ')]];$('#detail').hidden=false;$('#detail').innerHTML=`<div class="detailHead"><div class="badge">${x.type}</div><h2>${esc(x.title)}</h2><p>${esc(x.group)}</p></div>`+sec.filter(a=>a[1]).map(a=>`<section><h3>${esc(a[0])}</h3><div class="pre">${esc(String(a[1]))}</div></section>`).join('')+'<button id="closeDetail">بستن</button>';$('#closeDetail').onclick=()=>$('#detail').hidden=true;scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function investigate(){const symptom=$('#symptom').value.trim(),evidence=$('#evidence').value.trim(),text=norm(symptom+' '+evidence);if(!symptom){$('#investigation').innerHTML='<h2>Evidence Correlation</h2><p>اول Symptom را وارد کن.</p>';return}let pb=PLAYBOOKS.map(p=>{const hit=p.symptoms.filter(s=>text.includes(norm(s))).length;return {...p,score:hit+(text.includes(norm(p.title))?2:0)}}).sort((a,b)=>b.score-a.score)[0];if(!pb||pb.score===0)pb={title:'Layered Path Fault',layers:['L1/L2','L3','Transport','Service','Policy'],tests:['interface/link','ARP/ND','route/FIB','service probe','policy/logs'],rootCauses:['physical/link','neighbor resolution','routing','service','policy'],score:0};const first=text.includes('retrans')?'TCP delivery/ACK progression':text.includes('dhcp')||text.includes('ip نمی')?'DHCP transaction':text.includes('dns')?'DNS resolution':text.includes('ospf')?'OSPF adjacency/convergence':text.includes('vlan')?'802.1Q / switching':'Unknown — collect discriminating evidence';const related=DB.filter(x=>x.type==='lesson'&&(x.text.toLowerCase().includes(norm(pb.title).split(' ')[0])||pb.layers.some(l=>x.text.toLowerCase().includes(norm(l))))).slice(0,6);$('#investigation').innerHTML=`<h2>${esc(pb.title)}</h2><div class="pipeline">${['Symptom','Evidence','Hypotheses','Discriminating Tests','First Divergence','Root Cause','Verification'].map((x,i)=>`<span>${i+1}. ${x}</span>`).join('')}</div><h3>Hypotheses</h3><div class="hyp">${pb.rootCauses.map((x,i)=>`<div><b>${esc(x)}</b><strong>${Math.max(45,86-i*9)}%</strong><p>${esc('Evidence required: '+pb.tests[Math.min(i,pb.tests.length-1)])}</p></div>`).join('')}</div><h3>First Divergence</h3><div class="callout">${esc(first)}</div><h3>Discriminating Tests</h3><ol>${pb.tests.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h3>Related Knowledge</h3><div>${related.map(x=>`<button class="linkLesson" data-i="${DB.indexOf(x)}">${esc(x.title)}</button>`).join('')}</div><small>این تحلیل Offline و evidence-driven است؛ برای تجهیز واقعی تغییری اجرا نمی‌شود.</small>`;document.querySelectorAll('.linkLesson').forEach(b=>b.onclick=()=>{document.querySelector('[data-tab="learn"]').click();show(DB[+b.dataset.i])})}
function renderJourneys(){const box=$('#journeySelect');box.innerHTML=JOURNEYS.map((j,i)=>`<button data-j="${i}">${esc(j.title)}</button>`).join('');document.querySelectorAll('[data-j]').forEach(b=>b.onclick=()=>drawJourney(JOURNEYS[+b.dataset.j]));drawJourney(JOURNEYS[0])}
function drawJourney(j){$('#journey').innerHTML=`<div class="steps">${j.steps.map((s,i)=>`<div class="step"><b>${i+1}</b><span>${esc(s)}</span></div>`).join('')}</div><div class="evidence"><h3>Evidence to capture</h3>${j.evidence.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`}
function configDiff(){const a=$('#cfgA').value.split(/\r?\n/),b=$('#cfgB').value.split(/\r?\n/),out=[],setA=new Set(a.filter(Boolean));let risk=[];for(const x of a)if(x&&!b.includes(x))out.push(`<div class="minus">− ${esc(x)}</div>`);for(const x of b)if(x&&!a.includes(x))out.push(`<div class="plus">+ ${esc(x)}</div>`);const joined=b.join(' ').toLowerCase();if(/permit any|allow all|0\.0\.0\.0\/0/.test(joined))risk.push('Broad policy / least-privilege risk');if(/password|secret|community/.test(joined))risk.push('Credential material should be reviewed/redacted');if(/no shutdown/.test(joined))risk.push('Operational state change: verify maintenance scope');$('#diffOut').innerHTML=`<h2>Diff</h2>${out.join('')||'<p>تغییری پیدا نشد.</p>'}<h3>Risk Hints</h3>${risk.length?risk.map(x=>`<div class="risk">⚠ ${esc(x)}</div>`).join(''):'<div class="ok">No heuristic risk hint detected</div>'}<p><small>Heuristic review است؛ جایگزین change review انسانی نیست.</small></p>`}
function renderMastery(){const rows=PROFILE.competencies.slice(0,30);$('#masteryRows').innerHTML=rows.map((x,i)=>{const v=Math.min(100,(x.evidence||0)*100);return `<div class="master"><div><b>${esc(x.name)}</b><span>${v}% • ${x.lessons} درس</span></div><div class="bar"><i style="width:${v}%"></i></div><small>${esc(x.next)}</small></div>`}).join('')}

function v11Investigate(){
 const symptom=norm($('#v11Symptom').value), evidence=String($('#v11Evidence').value||'').trim(), text=norm(symptom+' '+evidence);
 if(!symptom){$('#v11Out').innerHTML='<div class="card">Symptom را وارد کن.</div>';return}
 const scored=(FAULTS.cases||[]).map(f=>{let score=0;for(const t of [f.title,f.symptom,...f.evidence])if(text.includes(norm(t)))score+=2;return {...f,score}}).sort((a,b)=>b.score-a.score);
 const best=scored[0]||null;
 const first=text.includes('discover')&&!text.includes('offer')?'DHCP Discover → Offer':text.includes('exstart')||text.includes('mtu')&&text.includes('ospf')?'OSPF ExStart/DBD exchange':text.includes('retrans')||text.includes('tcp')?'TCP segment → ACK progression':text.includes('servfail')||text.includes('dns')?'DNS resolver → authoritative response':text.includes('trunk')||text.includes('vlan')?'Trunk → VLAN allow/tag state':text.includes('firewall')||text.includes('acl')?'Packet → ordered policy rule':'Link → Neighbor → Route/FIB → Transport → Service';
 const chain=first.startsWith('DHCP')?['Client','DHCP Discover','Relay/Server','DHCP Offer']:first.startsWith('OSPF')?['Interface','Hello','Neighbor','DBD/LSDB']:first.startsWith('TCP')?['Sender','Segment','Receiver','ACK progression']:first.startsWith('DNS')?['Application','Resolver','Authoritative','Response']:first.startsWith('Trunk')?['Access VLAN','802.1Q Trunk','Allowed VLAN','Destination']:['Interface','ARP/ND','RIB/FIB','Transport/Service'];
 const tests=best?[...(best.evidence||[]),best.remediation]:['interface/link','ARP/ND','route/FIB','service probe','policy/logs'];
 const related=DB.filter(x=>x.type==='lesson').filter(x=>text.split(/\s+/).some(t=>t.length>3&&norm(x.text).includes(t))).slice(0,7);
 const deps=dependencyBlast(text);
 const hypotheses=best?[best]:[{title:'Layered network-path fault',symptom:'No protocol-specific discriminator yet',evidence:['Collect hard evidence first'],remediation:'Run low-risk tests from lower to higher layers',rollback:'No change until cause is verified'}];
 $('#v11Out').innerHTML=`<div class="v11grid"><div><h2>First Divergence</h2><div class="callout">${esc(first)}</div><h3>Evidence Chain</h3><div class="v11chain">${chain.map((x,i)=>`<div><b>${i+1}</b><span>${esc(x)}</span></div>`).join('')}</div></div><div><h2>Hypotheses</h2>${hypotheses.map((h,i)=>`<div class="hyp"><b>${esc(h.title)}</b><strong>${Math.max(55,90-i*12)}%</strong><p>${esc(h.symptom||'Evidence-aligned candidate cause')}</p><p><b>Falsifier:</b> ${esc((h.evidence||[]).join(', '))}</p><p><b>Verification:</b> ${esc(h.remediation||'Discriminating test required')}</p></div>`).join('')}</div></div><h3>Discriminating Tests</h3><ol>${tests.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h3>Dependency Blast Radius</h3><div class="dependencyGrid">${deps.map(d=>`<div class="dep"><b>${esc(d.name)}</b><span>${d.impact}% impact</span><small>${esc(d.why)}</small></div>`).join('')}</div><h3>Related Knowledge</h3><div>${related.map(x=>`<button class="linkLesson v11link" data-i="${DB.indexOf(x)}">${esc(x.title)}</button>`).join('')||'<small>برای ارتباط دقیق‌تر Evidence بیشتری وارد کن.</small>'}</div><p><small>Evidence Chain rule: نتیجه بدون Evidence + Falsifier تأییدشده، Root Cause قطعی محسوب نمی‌شود.</small></p>`;
 document.querySelectorAll('.v11link').forEach(b=>b.onclick=()=>{document.querySelector('[data-tab="learn"]').click();show(DB[+b.dataset.i])});
}
function dependencyBlast(text){
 const out=[];const add=(name,impact,why)=>out.push({name,impact,why});
 if(text.includes('dns')||text.includes('resolve')){add('Application',92,'Name resolution influences application setup');add('AD/Kerberos',84,'Service discovery and identity commonly depend on DNS')}
 if(text.includes('dhcp')||text.includes('ip نمی')){add('Host reachability',90,'Address, gateway and resolver state depend on DHCP');add('DNS',72,'Clients without valid resolver options lose name resolution')}
 if(text.includes('vlan')||text.includes('trunk')){add('DHCP Relay',86,'Broadcast domain placement controls relay reachability');add('Inter-VLAN Routing',82,'Missing VLAN/tag blocks routed reachability')}
 if(text.includes('ospf')||text.includes('route')){add('Applications',88,'Traffic delivery depends on valid RIB/FIB');add('Monitoring',71,'Management reachability follows the route path')}
 if(text.includes('firewall')||text.includes('acl')){add('Services',87,'Ordered policy can drop otherwise valid traffic');add('Observability',63,'Counters and logs distinguish policy faults')}
 if(text.includes('nat'))add('Internet Egress',94,'Private traffic needs translation and a return route');
 return out.slice(0,8)
}
function renderPassportV11(){
 const rows=PASSPORT.competencies||[];
 $('#v11Passport').innerHTML=rows.map(x=>`<div class="master"><div><b>${esc(x.name)}</b><span>${Math.round((x.weight||0)*100)}% weight</span></div><div class="bar"><i style="width:${Math.round((x.weight||0)*100)}%"></i></div><small>Inputs: ${(x.inputs||[]).map(esc).join(' • ')}</small></div>`).join('');
}
function renderFaultCatalogV11(){
 $('#v11Faults').innerHTML=(FAULTS.cases||[]).map(f=>`<div class="faultRow"><div><b>${esc(f.title)}</b><small>${esc(f.layer)} • ${esc(f.firstDivergence)}</small></div><button data-fault="${esc(f.id)}">Activate Case</button></div>`).join('');
 document.querySelectorAll('[data-fault]').forEach(b=>b.onclick=()=>{const f=(FAULTS.cases||[]).find(x=>x.id===b.dataset.fault);if(!f)return;$('#v11FaultOut').innerHTML=`<h3>${esc(f.title)}</h3><p>${esc(f.symptom)}</p><p><b>First Divergence:</b> ${esc(f.firstDivergence)}</p><p><b>Expected Evidence:</b> ${(f.evidence||[]).map(esc).join(' • ')}</p><p><b>Remediation:</b> ${esc(f.remediation)}</p><p><b>Rollback:</b> ${esc(f.rollback)}</p>`;document.getElementById('v11FaultOut').scrollIntoView({behavior:'smooth',block:'nearest'})});
}

async function init(){const [c,d,s,l,ai,aliases,pb,j,profile,evidence,deps,faults,passport]=await Promise.all([j('curriculum.json'),j('deep/expert_engineering.json'),j('deep/scenarios.json'),j('master/lab_catalog.json'),j('master/ai_playbooks.json'),j('search_aliases.json'),j('incident_playbooks_v10.json'),j('packet_journeys_v10.json'),j('adaptive_profile_v10.json'),j('evidence_chain_v11.json'),j('dependency_graph_v11.json'),j('failure_injection_v11.json'),j('engineering_passport_v11.json')]);ALIAS=aliases;PLAYBOOKS=pb.playbooks;JOURNEYS=j.journeys;PROFILE=profile;EVIDENCE=evidence;DEPS=deps;FAULTS=faults;PASSPORT=passport;DB=flat(c,d,s,l,ai);$('#stats').innerHTML=[['770','Core Lessons'],[d.metadata.lessonCount,'Deep Engineering'],[s.metadata.scenarioCount,'Scenarios'],[l.labs.length,'Labs'],[ai.modes.length,'AI Modes'],[DB.length,'Knowledge Objects']].map(x=>`<span class="stat"><b>${x[0]}</b><small>${x[1]}</small></span>`).join('');render();renderJourneys();renderMastery();renderPassportV11();renderFaultCatalogV11()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});$('#q').oninput=render;$('#type').onchange=render;$('#clear').onclick=()=>{$('#q').value='';$('#type').value='all';render()};$('#investigate').onclick=investigate;$('#v11Investigate').onclick=v11Investigate;$('#diff').onclick=configDiff;init().catch(e=>{document.body.insertAdjacentHTML('beforeend','<div class="fatal">Knowledge Base error: '+esc(e.message)+'</div>')});
